### ISSUE TITLE
Choice?

### ISSUE THREAD

**Issue by grodin** [RocketRace/setver#1]
I am completely sold on this revolutionary method of versioning software and intend to use it immediately in everything.

I just have one slight issue though: what flavour of set theory are we using here? It's all fine and dandy as long as our versions are finite sets, but I can imagine some Enterprises needing infinite version sets quite quickly and then we need to agree exactly what axioms we're using.

In order to keep this issue focused, are we accepting the Axiom of Choice in SetVer or not?

Once that is settled, then we will probably need to deal with issues about constructivism but I'll leave that for later...

**Comment by pulustelu** [comment]
Thanks for your consideration, and more importantly, thanks for fully embracing SetVer!

We've had a meeting with the Council about this, and there were a number of differing opinions. While there were a few council members that advocated for dropping the axiom of infinity and "sticking to sets that actually exist," they have since been terminated. The overall concensus is that ZF is "radical" and "tubuler [sic]".

Choice remains controversial. As a compromise, we've decided to standardize ZF in the next version of SetVer, and to declare the use of the axiom undefined behavior. Later versions may or may not change this political stance.

**Comment by pulustelu** [comment]
Version `{{}}` now addresses this!

**Comment by ant-arctica** [comment]
Choice is automatically true in SetVer, because SetVer only consists of hereditarily finite sets. You can't write down an infinite set as a finite string of `{` and `}`'s. So it is not a model of ZF, but a model of ZF - infinite (+ ¬infinity). This contradicts with the change introduced in `{{}}`, which claims that SetVer is a model of ZF.

**Comment by pulustelu** [comment]
> Choice is automatically true in SetVer, because SetVer only consists of hereditarily finite sets. You can't write down an infinite set as a finite string of `{` and `}`'s. So it is not a model of ZF, but a model of ZF - infinite (+ ¬infinity). This contradicts with the change introduced in `{{}}`, which claims that SetVer is a model of ZF.

Thank you for contacting SetVer customer support. We will process your inquiry and report back in [processing...] business days.
